-- 1. Create Core Multi-Tenant Tables

CREATE TABLE IF NOT EXISTS public.businesses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  industry TEXT,
  twilio_phone_number TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.business_users (
  user_id UUID REFERENCES auth.users(id) PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  role TEXT DEFAULT 'owner',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lisahq_admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);



-- Note: We assume business_facts already exists, so we alter it. If it doesn't, this will fail.
-- It's safer to drop it and recreate it for a clean slate with dummy data.
DROP TABLE IF EXISTS public.business_facts CASCADE;
CREATE TABLE public.business_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  opening_hours TEXT,
  general_info TEXT,
  ai_prompt_instructions TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(business_id)
);


-- 2. Modify Existing Tables to include business_id
-- WARNING: Removed destructive drops. Use IF NOT EXISTS.
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  name TEXT,
  email TEXT,
  phone TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  name TEXT,
  contact_info TEXT,
  vehicle_model TEXT,
  concern TEXT,
  status TEXT DEFAULT 'new',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Safely restore missing foreign keys if they were dropped by previous CASCADE commands
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'appointments_customer_id_fkey') THEN
        ALTER TABLE public.appointments
        ADD CONSTRAINT appointments_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 3. RLS Helper Function
CREATE OR REPLACE FUNCTION public.auth_business_id()
RETURNS UUID
LANGUAGE sql STABLE
AS $$
  SELECT business_id FROM public.business_users WHERE user_id = auth.uid()
$$;

-- Helper function to check if user is superadmin
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS BOOLEAN
LANGUAGE sql STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.lisahq_admins WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
  )
$$;

-- 4. Enable RLS
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lisahq_admins ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies

-- lisahq_admins: Only superadmins can read/write this table
DROP POLICY IF EXISTS "Superadmins can read admins" ON public.lisahq_admins;
CREATE POLICY "Superadmins can read admins" ON public.lisahq_admins FOR SELECT USING (is_superadmin());

-- businesses: Users can read their own business, superadmins can read/write all
DROP POLICY IF EXISTS "Users read own business" ON public.businesses;
CREATE POLICY "Users read own business" ON public.businesses FOR SELECT USING (id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Users update own business" ON public.businesses;
CREATE POLICY "Users update own business" ON public.businesses FOR UPDATE USING (id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Superadmins full access businesses" ON public.businesses;
CREATE POLICY "Superadmins full access businesses" ON public.businesses FOR ALL USING (is_superadmin());

-- business_users: User reads own mapping, superadmins read/write all
DROP POLICY IF EXISTS "User reads own mapping" ON public.business_users;
CREATE POLICY "User reads own mapping" ON public.business_users FOR SELECT USING (user_id = auth.uid() OR is_superadmin());
DROP POLICY IF EXISTS "Superadmins full access mapping" ON public.business_users;
CREATE POLICY "Superadmins full access mapping" ON public.business_users FOR ALL USING (is_superadmin());

-- business_facts: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read business_facts" ON public.business_facts FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert business_facts" ON public.business_facts FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update business_facts" ON public.business_facts FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete business_facts" ON public.business_facts FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- customers: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read customers" ON public.customers FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert customers" ON public.customers FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update customers" ON public.customers FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete customers" ON public.customers FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- leads: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read leads" ON public.leads FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert leads" ON public.leads FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update leads" ON public.leads FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete leads" ON public.leads FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- 6. Resource Management
CREATE TABLE IF NOT EXISTS public.resource_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL,
    label TEXT NOT NULL,
    fields JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.resource_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read resource_templates" ON public.resource_templates;
CREATE POLICY "Anyone can read resource_templates" ON public.resource_templates FOR SELECT USING (true);
DROP POLICY IF EXISTS "Superadmins full access resource_templates" ON public.resource_templates;
CREATE POLICY "Superadmins full access resource_templates" ON public.resource_templates FOR ALL USING (is_superadmin());

CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'available',
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant read resources" ON public.resources;
CREATE POLICY "Tenant read resources" ON public.resources FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant insert resources" ON public.resources;
CREATE POLICY "Tenant insert resources" ON public.resources FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant update resources" ON public.resources;
CREATE POLICY "Tenant update resources" ON public.resources FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant delete resources" ON public.resources;
CREATE POLICY "Tenant delete resources" ON public.resources FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- 7. Appointments Table
CREATE TABLE IF NOT EXISTS public.appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id),
    title TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'confirmed',
    notes TEXT,
    resource_id BIGINT REFERENCES public.resources(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant read appointments" ON public.appointments;
CREATE POLICY "Tenant read appointments" ON public.appointments FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant insert appointments" ON public.appointments;
CREATE POLICY "Tenant insert appointments" ON public.appointments FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant update appointments" ON public.appointments;
CREATE POLICY "Tenant update appointments" ON public.appointments FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant delete appointments" ON public.appointments;
CREATE POLICY "Tenant delete appointments" ON public.appointments FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- 8. Business Secrets Table
CREATE TABLE IF NOT EXISTS public.business_secrets (
    business_id UUID REFERENCES public.businesses(id) PRIMARY KEY,
    external_api_key TEXT,
    webhook_secret TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.business_secrets ENABLE ROW LEVEL SECURITY;
-- Only the server (service_role) and superadmins can access this table directly
-- Normal users cannot select from it via client APIs.
DROP POLICY IF EXISTS "Superadmins full access secrets" ON public.business_secrets;
CREATE POLICY "Superadmins full access secrets" ON public.business_secrets FOR ALL USING (is_superadmin());

-- 9. Call Logs Table (Audit Log for Twilio)
CREATE TABLE IF NOT EXISTS public.call_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) NOT NULL,
    to_phone TEXT NOT NULL,
    status TEXT DEFAULT 'initiated',
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant read call_logs" ON public.call_logs;
CREATE POLICY "Tenant read call_logs" ON public.call_logs FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
DROP POLICY IF EXISTS "Tenant insert call_logs" ON public.call_logs;
CREATE POLICY "Tenant insert call_logs" ON public.call_logs FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());

-- 10. Atomic Booking RPC
CREATE OR REPLACE FUNCTION book_appointment_atomic(
  p_business_id UUID,
  p_customer_id BIGINT,
  p_title TEXT,
  p_start_time TIMESTAMPTZ,
  p_end_time TIMESTAMPTZ,
  p_notes TEXT,
  p_resource_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_conflict_id UUID;
  v_new_appt_id UUID;
  v_result JSONB;
BEGIN
  -- Acquire transaction-level advisory lock to serialize booking requests
  IF p_resource_id IS NOT NULL THEN
     PERFORM pg_advisory_xact_lock(p_resource_id::integer);
  ELSE
     PERFORM pg_advisory_xact_lock(hashtext(p_business_id::text));
  END IF;

  -- 1. Check for overlapping time slots
  IF p_resource_id IS NOT NULL THEN
    SELECT id INTO v_conflict_id
    FROM public.appointments
    WHERE business_id = p_business_id
      AND resource_id = p_resource_id
      AND start_time < p_end_time
      AND end_time > p_start_time
    LIMIT 1;
  ELSE
    SELECT id INTO v_conflict_id
    FROM public.appointments
    WHERE business_id = p_business_id
      AND resource_id IS NULL
      AND start_time < p_end_time
      AND end_time > p_start_time
    LIMIT 1;
  END IF;

  -- 2. If conflict found, return error
  IF v_conflict_id IS NOT NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Der Zeitraum ist bereits belegt.');
  END IF;

  -- 3. Insert the appointment atomically
  INSERT INTO public.appointments (business_id, customer_id, title, start_time, end_time, notes, resource_id, status)
  VALUES (p_business_id, p_customer_id, p_title, p_start_time, p_end_time, p_notes, p_resource_id, 'confirmed')
  RETURNING id INTO v_new_appt_id;
  
  SELECT to_jsonb(a) INTO v_result FROM public.appointments a WHERE id = v_new_appt_id;

  RETURN jsonb_build_object('success', true, 'appointment', v_result);
END;
$$;