-- 1. Create Core Multi-Tenant Tables

CREATE TABLE public.businesses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  industry TEXT,
  twilio_phone_number TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.business_users (
  user_id UUID REFERENCES auth.users(id) PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  role TEXT DEFAULT 'owner',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.lisahq_admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Note: We assume business_facts already exists, so we alter it. If it doesn't, this will fail.
-- It's safer to drop it and recreate it for a clean slate with dummy data.
DROP TABLE IF EXISTS public.business_facts CASCADE;
CREATE TABLE public.business_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  opening_hours TEXT,
  general_info TEXT,
  ai_prompt_instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- 2. Modify Existing Tables to include business_id
-- For development, we drop and recreate customers and leads for a clean state
-- WARNING: This deletes existing data!
DROP TABLE IF EXISTS public.customers CASCADE;
CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  name TEXT,
  email TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

DROP TABLE IF EXISTS public.leads CASCADE;
CREATE TABLE public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) NOT NULL,
  name TEXT,
  contact_info TEXT,
  vehicle_model TEXT,
  concern TEXT,
  status TEXT DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. RLS Helper Function
CREATE OR REPLACE FUNCTION public.auth_business_id()
RETURNS UUID
LANGUAGE sql STABLE
AS $$
  SELECT business_id FROM public.business_users WHERE user_id = auth.uid()
$$;

-- Helper function to check if user is superadmin
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS BOOLEAN
LANGUAGE sql STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.lisahq_admins WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
  )
$$;

-- 4. Enable RLS
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lisahq_admins ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies

-- lisahq_admins: Only superadmins can read/write this table
CREATE POLICY "Superadmins can read admins" ON public.lisahq_admins FOR SELECT USING (is_superadmin());

-- businesses: Users can read their own business, superadmins can read/write all
CREATE POLICY "Users read own business" ON public.businesses FOR SELECT USING (id = auth_business_id() OR is_superadmin());
CREATE POLICY "Users update own business" ON public.businesses FOR UPDATE USING (id = auth_business_id() OR is_superadmin());
CREATE POLICY "Superadmins full access businesses" ON public.businesses FOR ALL USING (is_superadmin());

-- business_users: User reads own mapping, superadmins read/write all
CREATE POLICY "User reads own mapping" ON public.business_users FOR SELECT USING (user_id = auth.uid() OR is_superadmin());
CREATE POLICY "Superadmins full access mapping" ON public.business_users FOR ALL USING (is_superadmin());

-- business_facts: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read business_facts" ON public.business_facts FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert business_facts" ON public.business_facts FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update business_facts" ON public.business_facts FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete business_facts" ON public.business_facts FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- customers: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read customers" ON public.customers FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert customers" ON public.customers FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update customers" ON public.customers FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete customers" ON public.customers FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());

-- leads: Tenant isolation + superadmin full access
CREATE POLICY "Tenant read leads" ON public.leads FOR SELECT USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant insert leads" ON public.leads FOR INSERT WITH CHECK (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant update leads" ON public.leads FOR UPDATE USING (business_id = auth_business_id() OR is_superadmin());
CREATE POLICY "Tenant delete leads" ON public.leads FOR DELETE USING (business_id = auth_business_id() OR is_superadmin());
